/*
 * This source file was generated by the Gradle 'init' task
 */
package gurjar.singh.komal.javaLiveMusicBeatDetectionLib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
